export const GET_DROPDOWN_SURAT_IJIN_REQUEST =
  'GET_DROPDOWN_SURAT_IJIN_REQUEST';
export const GET_DROPDOWN_SURAT_IJIN_SUCCESS =
  'GET_DROPDOWN_SURAT_IJIN_SUCCESS';
export const GET_DROPDOWN_SURAT_IJIN_FAILURE =
  'GET_DROPDOWN_SURAT_IJIN_FAILURE';

export const GET_ALL_SURAT_IJIN_REQUEST = 'GET_ALL_SURAT_IJIN_REQUEST';
export const GET_ALL_SURAT_IJIN_SUCCESS = 'GET_ALL_SURAT_IJIN_SUCCESS';
export const GET_ALL_SURAT_IJIN_FAILURE = 'GET_ALL_SURAT_IJIN_FAILURE';

export const GET_SURAT_IJIN_BY_ID_REQUEST = 'GET_SURAT_IJIN_BY_ID_REQUEST';
export const GET_SURAT_IJIN_BY_ID_SUCCESS = 'GET_SURAT_IJIN_BY_ID_SUCCESS';
export const GET_SURAT_IJIN_BY_ID_FAILURE = 'GET_SURAT_IJIN_BY_ID_FAILURE';
