export const GET_ALL_SURAT_IJIN_REQUEST = 'GET_ALL_SURAT_IJIN_REQUEST';
export const GET_ALL_SURAT_IJIN_SUCCESS = 'GET_ALL_SURAT_IJIN_SUCCESS';
export const GET_ALL_SURAT_IJIN_FAILURE = 'GET_ALL_SURAT_IJIN_FAILURE';
