export const GET_ALL_SURAT_JALAN_REQUEST = 'GET_ALL_SURAT_JALAN_REQUEST';
export const GET_ALL_SURAT_JALAN_SUCCESS = 'GET_ALL_SURAT_JALAN_SUCCESS';
export const GET_ALL_SURAT_JALAN_FAILURE = 'GET_ALL_SURAT_JALAN_FAILURE';
